version: "3.8"

services:
  frontend:
    build: .
    container_name: realestate-frontend
    ports:
      - "3014:80"
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://62.72.21.81:3013